name: deploy action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
    - name: Migrate Wagtail
      run: |
        python mysite/manage.py migrate
    - name: Run Wagtail
      run: |
        (cd mysite && gunicorn -D mysite.wsgi:application --bind 0.0.0.0:8080)
    - name: Run Pelican
      run: |
        mkdir content
        pelican --ignore-cache content -s ./pelicanconf.py